### ISSUE TITLE
feature request: katon open w/ https instead of http

### ISSUE THREAD

**Issue by eddywashere** [typicode/katon#63]
It would be really nice to have an option to use https instead of http when using `katon open`. Maybe even force ssl, redirect to https. Also, it was really awesome to discover that ssl was even setup for katon :raised_hands:, maybe add a section for "ssl" or "https" to the docs? That was first thing I searched for.

If anyone else is interested in this, I just manually edited the following file in my global node modules directory - https://github.com/typicode/katon/blob/master/src/cli/commands/open.js#L9

**Comment by typicode** [comment]
Thanks for the suggestions and the feedback :)
I've updated the README and added an `--https` option to `katon open`.

Not sure yet if I would default to `https`. Mainly because the browser warning is so annoying and may scare first time users or beginners.

Was thinking about creating `katon http <app>` and `katon https <app>` too instead of `katon open`. It would make it faster to type but maybe less clear?

BTW, you can go to https://index.ka and access your servers from there.

**Comment by eddywashere** [comment]
I can see that being a bad first time exeperience. Just updated and everything looks good. Thanks!

**Comment by typicode** [comment]
Cool. You're welcome.
